[phases.setup]
nixPkgs = ["python3", "libGL", "mesa", "libgcc", "glibc", "libglvnd"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0", "libgomp1"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "uvicorn api.main:api --host 0.0.0.0 --port $PORT"
