[phases.setup]
nixPkgs = ["python3", "libGL", "mesa"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "uvicorn api.main:api --host 0.0.0.0 --port $PORT"
