[phases.setup]
nixPkgs = ["...", "libGL", "libGLU", "pkg-config", "cmake", "mesa", "libglvnd", "ffmpeg", "glib"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "uvicorn api.main:api --host 0.0.0.0 --port $PORT"
